## Chapter 2.

### Linear Algebra

Material:
    
    - http://www.deeplearningbook.org/contents/linear_algebra.html
    
Slides:
    - http://www.deeplearningbook.org/slides/02_linear_algebra.pdf
    
Reference:
    - https://docs.scipy.org/doc/numpy/reference/routines.linalg.html
    
    https://docs.scipy.org/doc/scipy-0.18.1/reference/tutorial/linalg.html

In [1]:
import numpy as np
from scipy import linalg

### numpy.ndarray

In [2]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [3]:
linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [4]:
b = np.array([[5,6]]) #2D array
b

array([[5, 6]])

In [5]:
b.T

array([[5],
       [6]])

In [6]:
A*b #not matrix multiplication!

array([[ 5, 12],
       [15, 24]])

In [7]:
A.dot(b.T) #matrix multiplication

array([[17],
       [39]])

In [8]:
b = np.array([5,6]) #1D array
b

array([5, 6])

In [9]:
b.T  #not matrix transpose!

array([5, 6])

In [10]:
A.dot(b)  #does not matter for multiplication

array([17, 39])